### ISSUE TITLE
Delete tenant: Parsing not correct

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/ansible-nae#57]
If I have a playbook that delete a tenant:
```
    - name: Delete Tenant
      aci_tenant:
        <<: *aci_login
        name: '{{ tenantName }}'
        descr: 'CDCI'
        state: absent
        output_path: 'config.json'
```

When the nae_prechange module is run the file is not parsed and we try to upload this to NAE: 
``` [{"fvTenant": {"attributes": {"dn": "uni/tn-tenant", "status": "deleted"}}}] ```

The expected format is:
``` {"totalCount": "1", "imdata": [{"fvTenant": {"attributes": {"name": "tenant", "descr": "CDCI", "dn": "uni/tn-tenant", "status": "deleted”}}}]}```

As a work around you can add another object to be deleted (say a VRF) and in that case the parsing works however there is then another issue: NAE returns this error: "msg": "Required attribute \"name\" missing for type \"fvTenant\"."

However ACI will accept the config, might be a cobraSDK limitation. Need to check on that more.
